### ISSUE TITLE
scrapli.exceptions.ScrapliTimeout: timed out reading from transport

### ISSUE THREAD

**Issue by gbs098** [scrapli/nornir_scrapli#139] opened 2023-02-13 15:11 UTC
Hello, tried to upgrade IOS-XE using "send_interactive"
`connection_options:
  scrapli:
    platform: cisco_iosxe
    timeout_transport: 300`
but have this issue on output 
```
  File "/home/py_user/projects_python/upgrade_os_cisco_project/.venv/lib/python3.10/site-packages/scrapli/channel/sync_channel.py", line 644, in send_inputs_interact
    buf += self._read_until_explicit_prompt(prompts=prompts)
  File "/home/py_user/projects_python/upgrade_os_cisco_project/.venv/lib/python3.10/site-packages/scrapli/channel/sync_channel.py", line 177, in _read_until_explicit_prompt
    read_buf.write(self.read())
  File "/home/py_user/projects_python/upgrade_os_cisco_project/.venv/lib/python3.10/site-packages/scrapli/channel/sync_channel.py", line 69, in read
    buf = self.transport.read()
  File "/home/py_user/projects_python/upgrade_os_cisco_project/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 216, in decorate
    return _multiprocessing_timeout(
  File "/home/py_user/projects_python/upgrade_os_cisco_project/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 108, in _multiprocessing_timeout
    return _handle_timeout(
  File "/home/py_user/projects_python/upgrade_os_cisco_project/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 134, in _handle_timeout
    raise ScrapliTimeout(message)
scrapli.exceptions.ScrapliTimeout: timed out reading from transport
```

**Comment by carlmontanari** [comment] 2023-02-13 15:40
seems pretty clear that there was a timeout...

without more information there is no way to help you and im going to close this. logs would be a good start. what does the upgrade process look like? does the box restart (then this will not work), etc.. if you want to provide enough information to get help, or much better: show an actual bug and how to reproduce it, then feel free to reopen.

**Closed by carlmontanari** 2023-02-13 15:40 UTC

**Comment by gbs098** [comment] 2023-02-13 15:52
I made o simple code what clear all inactive file from IOS-XE,
in log on cisco device it's show what my script work fine
log from cisco device
`
Feb 13 17:46:09: %INSTALL-5-INSTALL_START_INFO: Switch 1 R0/0: install_engine: Started install remove
Feb 13 17:46:29: %INSTALL-5-INSTALL_COMPLETED_INFO: Switch 1 R0/0: install_engine: Completed install remove
`
My  code:

`from nornir import InitNornir
from nornir_scrapli.tasks import send_interactive
from nornir_utils.plugins.functions import print_result

nr = InitNornir(config_file="config.yaml")


def clean_up(task):
    interact = [
        ("install remove inactive", f"{task.host}#"),
    ]
    task.run(task=send_interactive, interact_events=interact)


if __name__ == "__main__":
    result = nr.run(task=clean_up)
    print_result(result)`

**Comment by carlmontanari** [comment] 2023-02-13 16:04
`f"{task.host}#")` <- is this exactly the hostname of the device. and logs from scrapli would be much more useful.

**Comment by gbs098** [comment] 2023-02-13 16:13
@carlmontanari  Thx a lot, hostname from file and device was different

**Comment by gbs098** [comment] 2023-02-14 08:53
hello, sorry but i have issue with this output
My function
```
def _clean_up(task):
    """Delete inactive file from flash"""
    log.info(f"Run clean up for host {task.host}")
    interact = [
        ("install remove inactive", "Do you want to remove the above files? [y/n]", False),
        ("y", f"{task.host}#", False),
    ]
    task.run(task=send_interactive, interact_events=interact, timeout_ops=1800)
```

Log:
```
10:44:38 - INFO: sending interactive input: install remove inactive; expecting: Do you want to remove the above files? [y/n]; hidden_input: False
10:44:38 - DEBUG: write: 'install remove inactive'
10:44:38 - DEBUG: read: b'i'
10:44:38 - DEBUG: read: b'n'
10:44:38 - DEBUG: read: b's'
10:44:38 - DEBUG: read: b'ta'
10:44:38 - DEBUG: read: b'l'
10:44:38 - DEBUG: read: b'l'
10:44:38 - DEBUG: read: b' '
10:44:38 - DEBUG: read: b'r'
10:44:38 - DEBUG: read: b'e'
10:44:38 - DEBUG: read: b'm'
10:44:38 - DEBUG: read: b'o'
10:44:38 - DEBUG: read: b'v'
10:44:38 - DEBUG: read: b'e'
10:44:38 - DEBUG: read: b' '
10:44:38 - DEBUG: read: b'i'
10:44:38 - DEBUG: read: b'n'
10:44:38 - DEBUG: read: b'a'
10:44:38 - DEBUG: read: b'c'
10:44:38 - DEBUG: read: b't'
10:44:38 - DEBUG: read: b'i'
10:44:38 - DEBUG: read: b'v'
10:44:38 - DEBUG: read: b'e'
10:44:38 - DEBUG: write: '\n'
10:44:38 - DEBUG: read: b'\n'
10:44:49 - DEBUG: read: b'install_remove: START Tue Feb 14 10:44:49 UTC 2023\n'
10:44:53 - DEBUG: read: b'<5>%INSTALL-5-INSTALL_START_INFO: R0/0: install_engine: Started install remove\n'
10:45:23 - CRITICAL: operation timed out, closing connection
10:45:23 - DEBUG: closing transport connection to '*.*.*.*' on port '22'
10:45:23 - CRITICAL: encountered EOF reading from transport; typically means the device closed the connection
10:45:23 - DEBUG: transport connection to '*.*.*.*' on port '22' closed successfully
```
on cisco device when it's starting this command `install remove inactive` after this command it's took some minutes to make this proccess till device will ask remove file or not

Is should be like on cisco device
```
Clean-up

install remove inactive
Use this command to clean-up old installation files in case of insufficient space and to ensure that you have at least 1GB of space in flash, to expand a new image.

The following sample output displays the cleaning up of unused files, by using the install remove inactive command:
Switch# install remove inactive
install_remove: START Mon Jul 19 17:46:18 IST 2021
Cleaning up unnecessary package files
No path specified, will use booted path flash:packages.conf
Cleaning flash:
  Scanning boot directory for packages ... done.
  Preparing packages list to delete ... 
    cat9k_lite-rpbase.17.05.01.SPA.pkg
      File is in use, will not delete.
    cat9k_lite-rpboot.17.05.01.SPA.pkg
      File is in use, will not delete.
    cat9k_lite-srdriver.17.05.01.SPA.pkg
      File is in use, will not delete.
    cat9k_lite-webui.17.05.01.SPA.pkg
      File is in use, will not delete.
    packages.conf
      File is in use, will not delete.
  done.
  
The following files will be deleted:
[switch 1]:
/flash/cat9k_lite_iosxe.17.05.01.SPA.bin

Do you want to remove the above files? [y/n]y

[switch 1]:
Deleting file flash:cat9k_lite_iosxe.17.05.01.SPA.bin ... done.
SUCCESS: Files deleted.
--- Starting Post_Remove_Cleanup ---
Performing Post_Remove_Cleanup on all members
  [1] Post_Remove_Cleanup package(s) on switch 1
  [1] Finished Post_Remove_Cleanup on switch 1
Checking status of Post_Remove_Cleanup on [1]
Post_Remove_Cleanup: Passed on [1]
Finished Post_Remove_Cleanup
SUCCESS: install_remove  Mon Jul 19 17:47:20 IST 2021
Switch#
```

**Comment by carlmontanari** [comment] 2023-02-14 13:09
looks like timeout ops is not set. try w/ scrapli without nornir or drop a breakpoint in the nornir task to see if timeout value is getting passed in and why it is or is not getting set there.

**Comment by gbs098** [comment] 2023-02-14 13:48
I tried without nornir, using only scrapli
I set breackpoint on -> `response = conn.send_interactive(interact, timeout_ops=1200.0)`, and in breakpoint it's show
```
timeout_ops = 30.0
timeout_socket = 15.0
timeout_transport = 30.0
```
```
interact = [
    ("install remove inactive", "Do you want to remove the above files? [y/n]", False),
    ("y", "Sw-ISE-Test#", False),
]
conn = Scrapli(**device)
conn.open()
response = conn.send_interactive(interact, timeout_ops=1200.0)
conn.close()
```

Log:
```
15:39:26 - DEBUG: created transport 'open_cmd': '['ssh', '*.*.*.*', '-p', '22', '-o', 'ConnectTimeout=15', '-o', 'ServerAliveInterval=30', '-l', 'user', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-F', '/dev/null']'
15:39:32 - DEBUG: transport connection to '*.*.*.*' on port '22' opened successfully
15:39:32 - DEBUG: attempting in channel ssh authentication
15:39:32 - DEBUG: read: b'6.36s - pydevd: Sending message related to process being replaced timed-out after 5 seconds\n'
15:39:33 - DEBUG: read: b"Warning: Permanently added '*.*.*.*' (RSA) to the list of known hosts.\n"
15:39:35 - DEBUG: read: b'Password: '
15:39:35 - DEBUG: write: REDACTED
15:39:35 - DEBUG: write: '\n'
15:39:35 - DEBUG: read: b'\n'
15:39:35 - DEBUG: read: b'Sw-ISE-Test#'
15:39:35 - DEBUG: write: '\n'
15:39:35 - DEBUG: read: b'\n'
15:39:35 - DEBUG: read: b'Sw-ISE-Test#'
15:39:35 - INFO: attempting to acquire 'privilege_exec' privilege level
15:39:35 - DEBUG: determined current privilege level is one of '['privilege_exec']'
15:39:35 - DEBUG: determined current privilege level is target privilege level, no action needed
15:39:35 - INFO: sending channel input: terminal length 0; strip_prompt: True; eager: False
15:39:35 - DEBUG: write: 'terminal length 0'
15:39:35 - DEBUG: read: b'te'
15:39:35 - DEBUG: read: b'r'
15:39:35 - DEBUG: read: b'm'
15:39:35 - DEBUG: read: b'i'
15:39:35 - DEBUG: read: b'na'
15:39:35 - DEBUG: read: b'l'
15:39:35 - DEBUG: read: b' '
15:39:35 - DEBUG: read: b'l'
15:39:35 - DEBUG: read: b'e'
15:39:35 - DEBUG: read: b'n'
15:39:35 - DEBUG: read: b'gt'
15:39:35 - DEBUG: read: b'h 0'
15:39:35 - DEBUG: write: '\n'
15:39:35 - DEBUG: read: b'\n'
15:39:35 - DEBUG: read: b'Sw-ISE-Test#'
15:39:35 - INFO: sending channel input: terminal width 512; strip_prompt: True; eager: False
15:39:35 - DEBUG: write: 'terminal width 512'
15:39:35 - DEBUG: read: b't'
15:39:35 - DEBUG: read: b'e'
15:39:35 - DEBUG: read: b'r'
15:39:35 - DEBUG: read: b'm'
15:39:35 - DEBUG: read: b'i'
15:39:35 - DEBUG: read: b'n'
15:39:35 - DEBUG: read: b'a'
15:39:35 - DEBUG: read: b'l'
15:39:35 - DEBUG: read: b' '
15:39:35 - DEBUG: read: b'w'
15:39:35 - DEBUG: read: b'idt'
15:39:35 - DEBUG: read: b'h '
15:39:35 - DEBUG: read: b'512'
15:39:35 - DEBUG: write: '\n'
15:39:35 - DEBUG: read: b'\n'
15:39:35 - DEBUG: read: b'Sw-ISE-Test#'
15:39:35 - INFO: connection to '*.*.*.*' on port '22' opened successfully
15:42:34 - INFO: modifying driver timeout for current operation, temporary timeout_ops value: '1200.0'
15:42:37 - DEBUG: setting 'timeout_ops' value to '1200.0'
15:42:37 - INFO: sending interactive input: install remove inactive; expecting: Do you want to remove the above files? [y/n]; hidden_input: False
15:42:37 - DEBUG: write: 'install remove inactive'
15:42:37 - DEBUG: read: b'i'
15:42:37 - DEBUG: read: b'n'
15:42:37 - DEBUG: read: b'st'
15:42:37 - DEBUG: read: b'al'
15:42:37 - DEBUG: read: b'l r'
15:42:37 - DEBUG: read: b'e'
15:42:37 - DEBUG: read: b'm'
15:42:37 - DEBUG: read: b'o'
15:42:37 - DEBUG: read: b'v'
15:42:37 - DEBUG: read: b'e'
15:42:37 - DEBUG: read: b' '
15:42:37 - DEBUG: read: b'i'
15:42:37 - DEBUG: read: b'n'
15:42:37 - DEBUG: read: b'ac'
15:42:37 - DEBUG: read: b't'
15:42:37 - DEBUG: read: b'i'
15:42:37 - DEBUG: read: b'v'
15:42:37 - DEBUG: read: b'e'
15:42:37 - DEBUG: write: '\n'
15:42:37 - DEBUG: read: b'\n'
15:42:52 - DEBUG: read: b'install_remove: START Tue Feb 14 15:42:52 UTC 2023\n'
15:42:57 - DEBUG: read: b'<5>%INSTALL-5-INSTALL_START_INFO: R0/0: install_engine: Started install remove\n'
15:43:27 - CRITICAL: operation timed out, closing connection
15:43:27 - DEBUG: closing transport connection to '*.*.*.*' on port '22'
15:43:27 - CRITICAL: encountered EOF reading from transport; typically means the device closed the connection
15:43:27 - DEBUG: transport connection to '*.*.*.*' on port '22' closed successfully

```

**Comment by gbs098** [comment] 2023-02-14 13:50
After this line `15:42:57 - DEBUG: read: b'<5>%INSTALL-5-INSTALL_START_INFO: R0/0: install_engine: Started install remove\n'` Cisco start process what took some time and after show output for `Do you want to remove the above files? [y/n]y`

**Comment by gbs098** [comment] 2023-02-14 14:26
if I add
`"timeout_transport": 1200.0,`

```
device = {
    "host": "*.*.*.*",
    "auth_strict_key": False,
    "platform": "cisco_iosxe",
    "timeout_transport": 1200.0,
}
```
It's work and not get `timeout`

**Comment by carlmontanari** [comment] 2023-02-14 15:42
yep that makes sense, all the timeouts are documented here -> https://carlmontanari.github.io/scrapli/user_guide/advanced_usage/#timeouts

glad you got it sorted.
