### ISSUE TITLE
Plugin is not Registered

### ISSUE THREAD

**Issue by lastorel** [scrapli/nornir_scrapli#46] opened 2021-05-06 14:17 UTC
Hi, in Nornir 3.0.0 some plugins must be registered in order to be used. https://nornir.readthedocs.io/en/3.0.0/plugins/index.html
So I have excpetion while running simple get_prompt:
`In [109]: print(prompt_result["nord-pre-lf1"].result)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/home/ubuntu/PycharmProjects/tscrapli/venv/lib/python3.8/site-packages/nornir_scrapli/tasks/get_prompt.py", line 19, in get_prompt
    scrapli_conn = task.host.get_connection("scrapli", task.nornir.config)
  File "/usr/local/lib/python3.8/site-packages/nornir/core/inventory.py", line 440, in get_connection
    self.open_connection(
  File "/usr/local/lib/python3.8/site-packages/nornir/core/inventory.py", line 481, in open_connection
    plugin = ConnectionPluginRegister.get_plugin(conn_name)
  File "/usr/local/lib/python3.8/site-packages/nornir/core/plugins/register.py", line 75, in get_plugin
    raise PluginNotRegistered(f"plugin {name!r} is not registered")
nornir.core.exceptions.PluginNotRegistered: plugin 'scrapli' is not registered
`

Installed modules in my environment:
nornir==3.0.0
nornir-napalm==0.1.1
nornir-netbox==0.1.1
scrapli==2021.1.30
nornir-scrapli==2021.1.30
scrapli-netconf==2021.1.30

I collect my inventory by NetBoxInventory2 (nornir_netbox) and set credentials by transform_function. How should I define the ConnectionOptions for scrapli/scrapli_netconf to be used by nornir?

**Comment by carlmontanari** [comment] 2021-05-06 15:19
The examples dir contains working examples to use (for both "regular" ssh and netconf) you can find them [here](https://github.com/scrapli/nornir_scrapli/tree/master/examples). 

Out of an abundance of caution I retested the examples just now and they work as expected, so I'm going to close this as it is almost certainly not a bug.

If you do find a bug feel free to re-open, but please use `discussions` (preferred. [here](https://github.com/scrapli/nornir_scrapli/discussions)) or slack for general questions. If you do open a discussion/slack comment we will need more information (inventory files, and a minimum reproducible example) in order to see see what's going on. Thanks!

Carl

**Closed by carlmontanari** 2021-05-06 15:19 UTC

**Comment by lastorel** [comment] 2021-05-07 09:44
Thank you for your feedback! I hope your documentation will get a little bigger over time. Nice work!
