### ISSUE TITLE
Timeout while editing configuration via netconf

### ISSUE THREAD

**Issue by Kani999** [scrapli/nornir_scrapli#58] opened 2021-07-08 12:37 UTC
Hello, 

When I'm trying to execute the following code on the device with e.g. 20 lines of 'acls', the code runs ok, and I'm able to display the diff.

```python
def install_acl(task: Task, dry_run: False) -> Result:
    j2_template = template_file(
        task, 'access_list.j2', './templates', acls=task.host['group_acls'])
    xml_config = j2_template.result

    send_config_to_device = nr.run(
        task=netconf_edit_config, diff=True, config=xml_config, dry_run=dry_run, target=task.host['target'])

    return Result(
        host=task.host,
        result=send_config_to_device[task.host.name].result
    )
```
---

But when I add more than 20 ALC rules I end up with an error

```
Traceback (most recent call last):
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 43, in netconf_edit_config
    scrapli_response = scrapli_conn.edit_config(config=config, target=target)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli_netconf/driver/sync_driver.py", line 188, in edit_config
    raw_response = self.channel.send_input_netconf(response.channel_input)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli_netconf/channel/sync_channel.py", line 325, in send_input_netconf
    buf = self._read_until_prompt(buf=buf)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/channel/sync_channel.py", line 131, in _read_until_prompt
    buf += self.read()
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/channel/sync_channel.py", line 68, in read
    buf = self.transport.read()
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 94, in decorate
    return self._multiprocessing_timeout(
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 171, in _multiprocessing_timeout
    self._handle_timeout()
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 147, in _handle_timeout
    raise ScrapliTimeout(self.message)
scrapli.exceptions.ScrapliTimeout: timed out reading from transport
```
---

When I try to increase the timeouts:
  -   timeout_socket: timeout for establishing socket/initial connection in seconds
  -   timeout_transport: timeout for ssh|telnet transport in seconds
  -   timeout_ops: timeout for ssh channel operations

I end up with other exception

```
Traceback (most recent call last):
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/transport/plugins/system/ptyprocess.py", line 424, in read
    s = self.fileobj.read1(size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/transport/plugins/system/transport.py", line 126, in read
    buf = self.session.read(65535)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/transport/plugins/system/ptyprocess.py", line 429, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_edit_config.py", line 43, in netconf_edit_config
    scrapli_response = scrapli_conn.edit_config(config=config, target=target)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli_netconf/driver/sync_driver.py", line 188, in edit_config
    raw_response = self.channel.send_input_netconf(response.channel_input)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli_netconf/channel/sync_channel.py", line 325, in send_input_netconf
    buf = self._read_until_prompt(buf=buf)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/channel/sync_channel.py", line 131, in _read_until_prompt
    buf += self.read()
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/channel/sync_channel.py", line 68, in read
    buf = self.transport.read()
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 94, in decorate
    return self._multiprocessing_timeout(
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/decorators.py", line 172, in _multiprocessing_timeout
    return future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jankrupa/nornir_netconf/venv/lib/python3.8/site-packages/scrapli/transport/plugins/system/transport.py", line 133, in read
    raise ScrapliConnectionError(msg) from exc
scrapli.exceptions.ScrapliConnectionError: encountered EOF reading from transport; typically means the device closed the connection
```

---

The configuration 

- `groups.yml`

```yml
---
IOSXR:
  platform: iosxr
  port: 22
  data:
    target: candidate
    group_acls:
      my_acl_rules:
        rules:
          - {seq: 10, remark: XXX -
          - {seq: 20, action: permit, src: 1.2.3.4, mask: 0.0.0.0}
          - {seq: 30, remark: XXX -
          - {seq: 40, action: permit, src: 1.2.3.4, mask: 0.0.0.0}
         ........
          - {seq: 110, remark: XXX -
          - {seq: 120, action: permit, src: 1.2.3.4, mask: 0.0.0.0}
          - {seq: 130, remark: XXX -
          - {seq: 140, action: permit, src: 1.2.3.4, mask: 0.0.0.0}
        ...........

  connection_options:
    scrapli_netconf:
      port: 22
      extras:
        ssh_config_file: False
        auth_strict_key: False
        timeout_socket: 6000
        timeout_transport: 6000

```

Could you please help me with the problem?
Thank you

**Comment by carlmontanari** [comment] 2021-07-08 14:42
Hey @Kani999 thanks for opening this!

I think we'll almost certainly need logs to see whats going on. Very worst case I'll probably need to see the final payload. You can snag logs by adding the following to your script:

```
from scrapli.logging import enable_basic_logging

enable_basic_logging(file=True, level="debug")
```

That will dump a `scrapli.log` file in your working dir (or you can pass a string to file path to write logs to instead of `True`). If you dont want to post the logs here you can email me at carl dot r dot montanari at gmail. In the meantime you can try to add `transport: ssh2` under your `extras` there to see if using ssh2 transport solves this in the short term. 

Could you also provide the output of `pip list | grep scrapli` to see what versions you are using? 

Thanks!
Carl

**Comment by Kani999** [comment] 2021-07-09 06:35
@carlmontanari - I've created a project https://github.com/Kani999/nornir_netconf_scrapli_issue where is the script and logs with the errors too.

The versions are:
```
nornir-scrapli    2021.1.30
scrapli           2021.1.30
scrapli-community 2021.1.30
scrapli-netconf   2021.1.30
```

Error logs are there:
- https://github.com/Kani999/nornir_netconf_scrapli_issue/blob/main/logs/nornir.log
- https://github.com/Kani999/nornir_netconf_scrapli_issue/blob/main/scrapli.log

**Comment by Kani999** [comment] 2021-07-09 06:50
@carlmontanari 
After installing the `ssh2-python` package and setting the extras transport method to `ssh2` in the configuration, everything works. 
Thank you

**Comment by carlmontanari** [comment] 2021-07-09 15:04
> @carlmontanari - I've created a project https://github.com/Kani999/nornir_netconf_scrapli_issue where is the script and logs with the errors too.

Awesome, thanks for doing this! I'm glad ssh2 works, but of course I want system transport working too, so I will try to get this tested and see if I can see whats going on. I'll keep ya posted!

Carl

**Comment by carlmontanari** [comment] 2021-07-09 16:22
Hey @Kani999 I believe this may be a regression that is now fixed in develop. I just tested the repo you shared with an xrv9k and the current develop branch of scrapli netconf and things work as expected with system transport. If you wouldn't mind testing that out that would be great -- you can install that develop branch like: `pip install -e git+https://github.com/scrapli/scrapli_netconf.git@develop#egg=scrapli_netconf`

Thanks again for your help with this!

Carl

**Comment by Kani999** [comment] 2021-07-12 06:51
@carlmontanari I have installed the `develop` version of `scrapli_netconf` and I can confirm it works even with the `system transport` 
Is there any plan, when the patch will be published?

I appreciate your work

**Comment by carlmontanari** [comment] 2021-07-12 14:49
Awesome, thank you so much for confirming @Kani999 ! 

Yep, this will all go out to pypi on 2021.07.30! I'm planning on sticking to a twice yearly release cycle to try to bring some consistency/sanity to scrapli versions. I wrote a bit about it here: https://www.montanari.io/posts/2021/on_versioning_and_scrapli/

I'll go ahead and close this now since there is a fix, but feel free to reopen/open a new issue if anything else goes crazy 😁 

Carl

**Closed by carlmontanari** 2021-07-12 14:49 UTC
