### ISSUE TITLE
scrapli_channel.log is empty

### ISSUE THREAD

**Issue by gbieli** [scrapli/nornir_scrapli#122] opened 2022-05-23 14:52 UTC
Hi,

I've seen that you can specify a channel_log with scrapli. I tried that with nornir_scrapli, but my log file remains empty. Below are my settings and the task code. Any ideas what could be wrong or is this not supported with nornir?

defaults.yaml:
```
---
platform: ios
connection_options:
 scrapli:
  platform: cisco_iosxe
  port: 22
  extras:
   channel_log: True
   channel_log_mode: append
   ssh_config_file: True
   auth_strict_key: False
 scrapli_netconf:
  port: 830
  extras:
   ssh_config_file: True
   auth_strict_key: False
```

code snippet:
```
s_100 = nr.filter(name="s-100")
    command_results = s_100.run(name="print version", task=send_command, command="show version | i RELEASE")
    print_result(command_results)
```

libraries:
```
nornir-scrapli==2022.1.30
scrapli==2022.1.30.post1
scrapli-cfg==2022.1.30
scrapli-community==2022.1.30
scrapli-netconf==2022.1.30
```

Regards,
Gérard

**Comment by carlmontanari** [comment] 2022-05-23 15:45
Hey Gérard

Just did a quick check and wasn't able to replicate this -- "scrapli_channel.log" gets created and populated. May be worth checking to see if the underlying scrapli channel gets the log file set, you can check something like this: `nr.inventory.hosts["test"].connections["scrapli"].connection.channel.channel_log` (of course with your host instead of "test").

Carl

**Comment by carlmontanari** [comment] 2022-05-23 16:12
Oh... just realized -- you're going to need to set the log per *host* otherwise its all the same log file for all hosts and will probably just be stomping all over itself. I'm guessing thats whats going on here, sorry I didn't notice before.

Probably would be a good idea to have nornir_scrapli auto append a hostname or some uuid or something if a user just sets `True` for the channel log as in this case. Would you be interested in tackling that in a PR? I dont use nornir for anything so *wayyyy* low on my priority list 😁 

Carl

**Comment by gbieli** [comment] 2022-05-24 06:00
Thank you for pointing me into the right direction. I will see if I find a good solution, maybe a workaround in the first place. I cannot promise anything because I'm a little bit busy at the moment.

**Comment by carlmontanari** [comment] 2022-05-29 17:04
[This](https://github.com/scrapli/nornir_scrapli/commit/5c2b39c4ce68d24059993e8e0a83716b431620d3) should fix this issue for ya. Need to install develop branch for now, but will be in the next release.

Carl

**Comment by carlmontanari** [comment] 2022-06-01 23:51
Hey @gbieli sorry for slow response,

I wonder if a "better" (or worse? I honestly don't know!) solution is to manually close your connections. On channel close we close the channel log which would flush any remaining output I think. Maybe its totally cool to flush at every write but it feels heavy handed (I have literally no rational justification for that, it just *feels* like you shouldn't need/want to -- very open to being wrong on this 😁 ). 

I dont *think* nornir will close the connections automagically (but I could be wrong here too) so It may be something that *should* be being done by users. Could you maybe give that a shot and let us know? I'll reopen this to keep track of this!

Thanks a bunch!
Carl

**Comment by gbieli** [comment] 2022-06-07 16:18
Hi,

Sorry for the delay, I was in holidays.

If I do
```
nr.inventory.hosts["test"].connections["scrapli"].connection.close()
```
then I get:
```
scrapli.exceptions.ScrapliConnectionNotOpened: connection not opened, but attempting to call a method that requires an open connection, do you need to call 'open()'?
```

I also set a breakpoint in /home/user/Documents/venvs/ios_nornir_examples/lib/python3.8/site-packages/scrapli/driver/base/sync_driver.py:107 -> close() then I see that this method is being called after the "send_command" task has been executed.

Regards,
Gérard

**Comment by carlmontanari** [comment] 2022-06-07 23:07
> I also set a breakpoint in /home/user/Documents/venvs/ios_nornir_examples/lib/python3.8/site-packages/scrapli/driver/base/sync_driver.py:107 -> close() then I see that this method is being called after the "send_command" task has been executed.

Ah ok cool guess nornir is closing things. will try to take another peak at this this weekend, thanks for the update and hope you had a nice holiday!

carl

**Comment by carlmontanari** [comment] 2022-06-18 17:18
Hey @gbieli 

Sorry for the delay yet again! So... I did a bit of reading in the docs on open/close/flush and it seems that `close` that we call on the channel log *should* call flush ... the source for that is in C but it does look like it calls flush prior to closing (though I have no idea what im looking at in C 😁 ). So... since I don't have a great setup with lots of devices at the moment and im unable to recreate this I'm wondering if you would mind moving that flush from the sync channel over to the base_channel close method. Basically just call flush prior to calling close in there to see if that works. The other thing I was thinking we could try is to set the channel log buffering to 0 -- from what I was reading it looks like the BinaryIO object will have a buffer of 8192 (on my laptop at least, but could be 4096 too on some systems) -- I would imagine by setting the buffer to 0 we would effectively never need flush (this is a bit of guessing though). You can set that in the base channel open method where we create the channel log, something like this:

```python
                self.channel_log = open(  # pylint: disable=W1514,R1732
                    channel_log_destination,
                    mode=f"{self._base_channel_args.channel_log_mode}b",  # type: ignore
                    buffering=0,
                )
``` 

Thanks for sticking with me on this one!

Carl

**Comment by carlmontanari** [comment] 2022-07-02 19:31
Hey @gbieli -- I'm going to close this for now since I haven't been able to reproduce it which makes it very difficult to fix for real, but defo feel free to re-open if you can spare some time to help investigate further. Thanks again for all your help looking into this!

Carl

**Closed by carlmontanari** 2022-07-02 19:31 UTC
